### ISSUE TITLE
Date in video name is off by 1 month

### ISSUE THREAD

**Issue by Xenon1** [yetanotherzacotp/automated-obs-record-and-upload#1]
It looks like when the videos title is being auto generated, the month is off by 1 month
![image](https://github.com/yetanotherzacotp/automated-obs-record-and-upload/assets/28608526/b0bdc89c-4743-45f7-adbc-4f31bb1f3b5d)

funny enough when i try the section of code in isolation its correct
![image](https://github.com/yetanotherzacotp/automated-obs-record-and-upload/assets/28608526/0d13e388-59b9-4f98-9e20-0dd8b2f2a234)

I would maybe try `getUTCMonth()` instead. but thats all i got lol

**Comment by yetanotherzacotp** [comment]
Hey! Thanks for the reminder - I had this fixed on my local already. Just pushed up this and some other changes, will make a new release executable in a minute as well

**Comment by yetanotherzacotp** [comment]
New version ([v0.0.3](https://github.com/yetanotherzacotp/automated-obs-record-and-upload/releases/tag/v0.0.3)) with this fix and more officially published!

EDIT: Use [v0.0.4](https://github.com/yetanotherzacotp/automated-obs-record-and-upload/releases/tag/v0.0.4) instead. There was a critical bug in v0.0.3
